require("bcmyers.globals")
require("bcmyers.config")
require("bcmyers.plugins")

require("bcmyers.plugins.autopairs")
require("bcmyers.plugins.catppuccin")
require("bcmyers.plugins.comment")
require("bcmyers.plugins.copilot")
require("bcmyers.plugins.crates")
require("bcmyers.plugins.fidget")
require("bcmyers.plugins.lsputils")
require("bcmyers.plugins.lualine")
require("bcmyers.plugins.tree")
require("bcmyers.plugins.treesitter")
require("bcmyers.plugins.trim")

require("bcmyers.plugins.mason")
require("bcmyers.plugins.dap")
require("bcmyers.plugins.lspconfig")
require("bcmyers.plugins.null_ls")
-- require("bcmyers.plugins.cmp")
-- require("bcmyers.plugins.formatter")
-- require("bcmyers.plugins.lsp-utils")
-- require("bcmyers.plugins.telescope")
-- require("bcmyers.plugins.treesitter")

-- require("nvim-dap-virtual-text").setup({})

require("bcmyers.colors")
