{
  pkgs,
  promptPackage,
  unstablePkgs,
  ...
}:
{
  home.packages =
    # Mature command-line and build tools follow the host's primary package set.
    (with pkgs; [
      age
      arp-scan
      autoconf
      automake
      bazel-buildtools
      bazelisk
      btop
      bzip2
      clang-tools
      coreutils
      curl
      diffutils
      doctl
      fd
      gcc
      gettext
      gh
      gnumake
      graphviz
      htop
      hyperfine
      jq
      just
      luarocks
      moreutils
      nerd-fonts.inconsolata
      ninja
      nmap
      openssl
      pandoc
      patchutils
      pkg-config
      qrencode
      restic
      ripgrep
      rsync
      shellcheck
      shfmt
      skopeo
      tree
      tree-sitter
      unzip
      wget
      xz
      yarn
      yq-go
      zip
    ])
    # Fast-moving language toolchains and developer tools follow unstable on
    # both platforms.
    ++ (with unstablePkgs; [
      cargo-update
      cmake
      go
      gotools
      gopls
      jujutsu
      lua-language-server
      nixd
      nixfmt
      nodejs_26
      opentofu
      pi-coding-agent
      prettier
      pulumi
      python3
      rustup
      sops
      sqlx-cli
      starpls
      stylua
      tofu-ls
      trunk
      typescript-language-server
      uv
    ])
    ++ [ promptPackage ];
}
